[[bin]]
name = "PSummary"
path = "Source/Library.rs"

[[bin]]
name = "Summary"
path = "Source/Library.rs"

[build-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
toml = { version = "1.1.4" }

[dependencies]
chrono = { version = "0.4.45" }
clap = { features = ["derive"], version = "4.6.5" }
dashmap = { version = "6.2.1" }
futures = { version = "0.3.33" }
git2 = { version = "0.21.0" }
itertools = { version = "0.15.0" }
num_cpus = { version = "1.17.0" }
rayon = { version = "1.12.0" }
regex = { version = "1.13.1" }
tokio = { version = "1.53.1", features = ["full"] }
unbug = { version = "0.5.0" }
walkdir = { version = "2.5.0" }

[features]
default = []

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Summary"
description = "Summary 🗣️"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "psummary"
repository = "https://github.com/PlayForm/Summary.git"
version = "0.1.5"
