[[bin]]
name = "PSummary"
path = "Source/Library.rs"

[[bin]]
name = "Summary"
path = "Source/Library.rs"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "0.9.10" }

[dependencies]
chrono = { version = "0.4.42" }
clap = { features = ["derive"], version = "4.5.54" }
dashmap = { version = "6.1.0" }
futures = { version = "0.3.31" }
git2 = { version = "0.20.3" }
itertools = { version = "0.14.0" }
num_cpus = { version = "1.17.0" }
rayon = { version = "1.11.0" }
regex = { version = "1.12.2" }
tokio = { version = "1.49.0", features = ["full"] }
unbug = { version = "0.4.0" }
walkdir = { version = "2.5.0" }

[features]
default = []

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Summary"
description = "Summary 🗣️"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "psummary"
repository = "https://github.com/PlayForm/Summary.git"
version = "0.1.4"
